argon2-cffi==20.1.0
async-generator==1.10
attrs==20.2.0
backcall==0.2.0
beautifulsoup4==4.9.3
bleach==3.2.1
certifi==2020.6.20
cffi==1.14.0
chardet==3.0.4
click==7.1.2
conda==4.9.1
conda-build==3.20.5
conda-package-handling==1.7.0
confuse==1.4.0
cryptography==2.9.2
cycler==0.10.0
dataclasses==0.6
decorator==4.4.2
defusedxml==0.6.0
dnspython==2.0.0
entrypoints==0.3
feather-format==0.4.1
filelock==3.0.12
freeze==3.0
future==0.18.2
glob2==0.7
htmlmin==0.1.12
idna==2.9
ImageHash==4.2.0
ipykernel==5.3.4
ipython==7.18.1
ipython-genutils==0.2.0
ipywidgets==7.5.1
japanize-matplotlib==1.1.3
jedi==0.17.2
Jinja2==2.11.2
joblib==0.17.0
jpholiday==0.1.5
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==6.1.7
jupyter-console==6.2.0
jupyter-core==4.6.3
jupyterlab-pygments==0.1.2
kiwisolver==1.3.1
libarchive-c==2.9
lightgbm==3.0.0
llvmlite==0.35.0
MarkupSafe==1.1.1
matplotlib==3.3.2
missingno==0.4.2
mistune==0.8.4
mkl-fft==1.2.0
mkl-random==1.1.1
mkl-service==2.3.0
nbclient==0.5.1
nbconvert==6.0.7
nbformat==5.0.8
nest-asyncio==1.4.2
networkx==2.5
notebook==6.1.4
numba==0.52.0
numpy==1.19.2
olefile==0.46
packaging==20.4
pandas==1.1.4
pandas-profiling==2.9.0
pandocfilters==1.4.3
parso==0.7.0
pexpect==4.8.0
phik==0.10.0
pickleshare==0.7.5
Pillow==8.0.0
pkginfo==1.6.0
prometheus-client==0.8.0
prompt-toolkit==3.0.8
psutil==5.7.2
ptyprocess==0.6.0
pyarrow==2.0.0
pycosat==0.6.3
pycparser==2.20
Pygments==2.7.1
pyOpenSSL==19.1.0
pyparsing==2.4.7
pyrsistent==0.17.3
PySocks==1.7.1
python-dateutil==2.8.1
python-etcd==0.4.5
pytz==2020.1
PyWavelets==1.1.1
PyYAML==5.3.1
pyzmq==19.0.2
qtconsole==4.7.7
QtPy==1.9.0
requests==2.23.0
ruamel-yaml==0.15.87
scikit-learn==0.23.2
scipy==1.5.3
seaborn==0.11.0
Send2Trash==1.5.0
signate==0.9.7
six==1.14.0
slicer==0.0.3
soupsieve==2.0.1
tabulate==0.8.7
tangled-up-in-unicode==0.0.6
terminado==0.9.1
testpath==0.4.4
threadpoolctl==2.1.0
torch==1.7.0
torchelastic==0.2.1
torchvision==0.8.0
tornado==6.1
tqdm==4.46.0
traitlets==5.0.5
typing-extensions==3.7.4.3
urllib3==1.25.8
visions==0.5.0
wcwidth==0.2.5
webencodings==0.5.1
wget==3.2
widgetsnbextension==3.5.1
xgboost==1.3.0.post0